const properties = {
  propertyGroup: {
    name: "Peak Accommodation",
    properties: [
      {
        id: "Krook",
        name: "The Krook",
        address: "119 Upton Street, Wānaka 9305, New Zealand",
        type: "House",
        units: 1,
        bedrooms: 5,
        beds: 7,
        bathrooms: 4,
        sleeps: 14,
        leaseType: "Short Term Accommodation",
        agent: "Wanaka Selection",
        comments: "3 double 4 single",
        imageUrl: "https://www.peakaccommodation.co.nz/wp-content/uploads/2019/02/the-krook-wanaka-holiday-house-SD026.jpg",
      },
      {
        id: "Tenby Apartments",
        name: "Tenby Apartments",
        address: "125 Tenby Street, Wānaka 9305, New Zealand",
        type: "Apartments",
        units: 4,
        bedrooms: 6,
        beds: 12,
        bathrooms: 6,
        sleeps: null,
        leaseType: "Short Term Accommodation",
        agent: "Wanaka Selection",
        comments: null,
        imageUrl: "https://www.peakaccommodation.co.nz/wp-content/uploads/2019/02/peak-apartments-web-whitebg-wanaka-accommodation.jpg",
      },
      {
        id: "Dragonfly",
        name: "Dragonfly",
        address: "41 McDougall Street, Wānaka 9305, New Zealand",
        type: "House",
        units: 1,
        bedrooms: 3,
        beds: 4,
        bathrooms: 2,
        sleeps: 6,
        leaseType: "Short Term Accommodation",
        agent: "Wanaka Selection",
        comments: null,
        imageUrl: "https://www.peakaccommodation.co.nz/wp-content/uploads/2019/02/dragonfly_cottage_12-800x600.jpg",
      },
      {
        id: "Dungarvon Apartments",
        name: "Dungarvon Apartments",
        address: "45 Dungarvon Street, Wānaka 9305, New Zealand",
        type: "Apartments",
        units: 8,
        bedrooms: 27,
        beds: 54,
        bathrooms: null,
        sleeps: null,
        leaseType: "Short Term Accommodation",
        agent: "Wanaka Selection",
        comments: null,
        imageUrl: "https://www.peakaccommodation.co.nz/wp-content/uploads/2019/02/upton-house-holiday-accommodation-wanaka-LD8_8734-1024x582.jpg",
      },
      {
        id: "Ahurei",
        name: "Ahurei",
        address: "208 Brownston Street, 9305 Wānaka, New Zealand",
        type: "Apartments",
        units: 7,
        bedrooms: 13,
        beds: 26,
        bathrooms: null,
        sleeps: null,
        leaseType: "Short Term Accommodation",
        agent: "Wanaka Selection",
        comments: null,
        imageUrl: "https://www.peakaccommodation.co.nz/wp-content/uploads/2019/02/peak-accommodation-web-wanaka-accommodation.jpg",
      },
      {
        id: "Pembroke - Lodge",
        name: "Pembroke - Lodge",
        address: "200 Brownston Street, 9305 Wānaka, New Zealand",
        type: "House",
        units: 1,
        bedrooms: 3,
        beds: 4,
        bathrooms: 2,
        sleeps: 6,
        leaseType: "Short Term Accommodation",
        agent: "Wanaka Selection",
        comments: "2 double 2 single",
        imageUrl: "https://www.peakaccommodation.co.nz/wp-content/uploads/2019/02/pembroke-lodge_06.jpg",
      },
      {
        id: "Pembroke - Villa",
        name: "Pembroke - Villa",
        address: "200 Brownston Street, 9305 Wānaka, New Zealand",
        type: "House",
        units: 1,
        bedrooms: 2,
        beds: 3,
        bathrooms: 1,
        sleeps: 4,
        leaseType: "Short Term Accommodation",
        agent: "Wanaka Selection",
        comments: "1 double 2 single",
        imageUrl: "https://www.peakaccommodation.co.nz/wp-content/uploads/2019/02/pembroke-villa-0615.jpg",
      },
      {
        id: "Pinot",
        name: "Pinot Cottage",
        address: "131 Warren Street, 9305 Wānaka, New Zealand",
        type: "House",
        units: 1,
        bedrooms: 2,
        beds: 3,
        bathrooms: 2,
        sleeps: 4,
        leaseType: "Short Term Accommodation",
        agent: "Wanaka Selection",
        comments: "1 double 2 single",
        imageUrl: "https://www.peakaccommodation.co.nz/wp-content/uploads/2019/02/pinot_cottage_141.jpg",
      },
      {
        id: "Kylies Castle",
        name: "Kylies Castle",
        address: "35 Youghal Street, Wānaka 9305, New Zealand",
        type: "House",
        units: 1,
        bedrooms: 5,
        beds: 7,
        bathrooms: 4,
        sleeps: 14,
        leaseType: "Short Term Accommodation",
        agent: "Wanaka Selection",
        comments: "5 double 2 single",
        imageUrl: "https://www.peakaccommodation.co.nz/wp-content/uploads/2019/02/wanaka-holiday-home-accommodation-Kylies-SD011.jpg",
      },
      {
        id: "McDougall Cottage",
        name: "McDougall Cottage",
        address: "37 McDougall Street, Wānaka 9305, New Zealand",
        type: "House",
        units: 1,
        bedrooms: 3,
        beds: 4,
        bathrooms: 2,
        sleeps: 6,
        leaseType: "Short Term Accommodation",
        agent: "Wanaka Selection",
        comments: "2 double 2 single",
        imageUrl: "https://www.peakaccommodation.co.nz/wp-content/uploads/2019/02/wanaka-holiday-house-mcdougalls_cottage_6.jpg",
      },
    ],
  },
};
